config/routes.rb
Rails.application.routes.draw do

  get 'register' => 'users#new', as: 'users'
  post 'register' => 'users#create'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  get 'logout' => 'sessions#destroy'

  get 'project_registration' => 'projects#new', as: 'projects'
  post 'project_registration' => 'projects#create'
  post 'project_delete' => 'projects#destroy'
  get 'projects/edit' => 'projects#edit', as: 'project'
  post 'projects/update'
  get 'projects/viewproject'
  post 'projects/viewproject' => 'reviews#create'

  get 'my_project' => 'projects#show'

  get 'admin_panel' => 'sessions#admin_panel'
  post 'admin_panel' => 'sessions#password_changed'

  get 'achievement/show'
  get 'achievement/new', as:'achievements'
  post 'achievement/new' => 'achievement#create'
  post 'achievement/destroy'

  get 'users/show_achievement'

  get 'show' => 'sessions#show'

  get 'review/show'
  get 'review/new', as:'reviews'
  post 'review/new' => 'review#create'

  get 'confirm/:id' => 'sessions#confirmation'

  get 'home/index'

  root 'home#index'

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  helper_method :getTopProjects


  def index
    projects = Project.all
    @topProj = getTopProjects(projects)
    @newProj = getNewProjects(projects)

  end



  private
  def getTopProjects(projects)
    return projects.order(rating: :desc).limit(4)
  end

  def getNewProjects(projects)
    return projects.order(created_at: :desc).limit(4)
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<script>
  $('document').ready(function() {
    setTimeout(function() {
      $('.projectAchievement').slideUp();
    }, 2000);
  });
</script>
<div class="row">
  <div class="project-container">
    <div class="row">
      <% if flash[:added].present? %>
          <div class="col-sm-4"></div>
          <div class="projectAchievement">
            <h3>Login bonus:</h3>
            <%= image_tag 'coin.png', size:'100x100' %>
            <%= flash[:added] %>
          </div>
          <div class="col-sm-4"></div>
      <% end %>
    </div>
  </div>
</div>


<div class="row">
  <div class="project-container">
    <div class="row">
      <div class="project-container-title">
        <h2>Top Projects</h2>
      </div>
    </div>
    <div class="row">
      <% if @topProj.any? %>
        <% @topProj.each do |tp| %>
          <div class="project-container-item">
            <% if tp.pictures[0] != nil %>
              <%= image_tag tp.pictures[0], size:'250x250', style:'padding-top:20px' %>
            <% else %>
              <img src="http://wordpress.smartaddons.com/themes/sw_chamy/wp-content/themes/sw_chamy/assets/img/no-thumbnail.png" width="250px" height="250px" style="padding-top:20px"/>
            <% end %>
            <div class="project-description">
              <h3><%= tp.title %></h3>
              <%= tp.description %>
            </div>
            <% if current_user && current_user.isAdmin %>
              <div class="project-edit-delete">
                <%= button_to 'Delete', project_delete_path(toDelete: tp.id), class:"button"%>
              </div>
              <% elsif current_user %>
              <div class="project-edit-delete">
                <%= link_to 'View', projects_viewproject_path(toFind: tp.id), class:"button"%>
                <%#= button_to 'View', projects_viewproject_path(toFind: tp.id), class:"button"%>
              </div>
            <% end %>
          </div>
        <% end %>
      <% else %>
        <div class="project-container-item">
          There are no projects
        </div>
      <% end %>
    </div>

    <div class="row">
      <div class="project-container-title">
        <h2>New Projects</h2>
      </div>
    </div>
    <div class="row">
      <% if @newProj.any? %>
        <% @newProj.each do |np| %>
          <div class="project-container-item">
            <% if np.pictures[0] != nil %>
              <%= image_tag np.pictures[0], size:'250x250', style:'padding-top:20px' %>
            <% else %>
              <img src="http://wordpress.smartaddons.com/themes/sw_chamy/wp-content/themes/sw_chamy/assets/img/no-thumbnail.png" width="250px" height="250px" style="padding-top:20px"/>
            <% end %>
            <div class="project-description">
              <h3><%= np.title %></h3>
              <%= np.description %>
            </div>
            <% if current_user && current_user.isAdmin %>
              <div class="project-edit-delete">
                <%= button_to 'Delete', project_delete_path(toDelete: np.id), class:"button"%>
              </div>
              <% elsif current_user %>
              <div class="project-edit-delete">
                <%= link_to 'View', projects_viewproject_path(toFind: np.id), class:"button"%>
                <%#= button_to 'View', projects_viewproject_path(toFind: tp.id), class:"button"%>
              </div>
            <% end %>
          </div>
        <% end %>
      <% else %>
      <div class="project-container-item">
        There are no projects
      </div>
      <% end %>
    </div>
  </div>
</div>