config/routes.rb
Rails.application.routes.draw do

  get 'register' => 'users#new', as: 'users'
  post 'register' => 'users#create'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  get 'logout' => 'sessions#destroy'

  get 'project_registration' => 'projects#new', as: 'projects'
  post 'project_registration' => 'projects#create'
  post 'project_delete' => 'projects#destroy'
  get 'projects/edit' => 'projects#edit', as: 'project'
  post 'projects/update'
  get 'projects/viewproject'
  post 'projects/viewproject' => 'reviews#create'

  get 'my_project' => 'projects#show'

  get 'admin_panel' => 'sessions#admin_panel'
  post 'admin_panel' => 'sessions#password_changed'

  get 'achievement/show'
  get 'achievement/new', as:'achievements'
  post 'achievement/new' => 'achievement#create'
  post 'achievement/destroy'

  get 'users/show_achievement'

  get 'show' => 'sessions#show'

  get 'review/show'
  get 'review/new', as:'reviews'
  post 'review/new' => 'review#create'

  get 'confirm/:id' => 'sessions#confirmation'

  get 'home/index'

  root 'home#index'

end

app/models/achievement.rb
class Achievement < ActiveRecord::Base
  has_and_belongs_to_many :users
  has_many :pictures
  serialize :pictures
  mount_uploaders :pictures, PictureUploader


  validates :title,
            :uniqueness => true,
            :presence => true,
            :length => {
              in: 5..50,
              message: "length should be between 5 and 50 characters"
            }

  validates :description,
            :presence => true,
            :length => {
              in: 5..5000,
              message: "length should be between 5 and 500 characters"
            }

end

app/controllers/achievement_controller.rb
class AchievementController < ApplicationController
  def new
    if current_user && current_user.isAdmin
      @new_achievement = Achievement.new
    else
      redirect_to root_url
    end
  end

  def create
    @new_achievement = Achievement.new(achievement_params)

    if @new_achievement.save
      redirect_to achievement_show_path, :notice => "Achievement added!"
    else
      render "new"
    end
  end

  def show
    @achievements = Achievement.all
  end

  def destroy
    toDelete = Achievement.find(params[:toDelete])
    toDelete.destroy

    redirect_to achievement_show_path
  end

  private
  def achievement_params
    params.require(:achievement).permit(:title, :description, {pictures: []})
  end

end

app/helpers/achievement_helper.rb
module AchievementHelper
end

app/views/achievement/new.html.erb
<div class="row">
  <div class="col-md-4">
    <!-- empty -->
  </div>
  <div class="form_input">
    <%= form_for @new_achievement do |f|%>
        <p><%= f.text_field :title, class:"input_field col-xs-12", placeholder:'Title' %></p>
        <p><%= f.text_area :description, class:"input_field2 col-xs-12", placeholder:'Description' %></p>
        <p><%= f.file_field :pictures, multiple: true %></p>
        <p><%= f.submit "Add", class:'button' %></p>
        <% if @new_achievement.errors.any? %>
          <p class="alert">
            <% @new_achievement.errors.full_messages.each do |e| %>
              <%= e %><br/>
            <% end %>
          </p>
        <% end %>
    <% end %>
  </div>
  <div class="col-md-4">
    <!-- empty -->
  </div>
</div>

app/views/achievement/show.html.erb
<div class="row">
  <div class="project-container">
    <div class="row">
      <div class="project-container-title">
        <h2>Achievements</h2>
      </div>
    </div>
    <% i = 0 %>
    <div class="row">
      <% if @achievements.any? %>
        <% @achievements.each do |a| %>
          <% i = i + 1 %>
          <div class="project-container-item">
            <% if a.pictures[0] != nil %>
              <%= image_tag a.pictures[0],class:'col-xs-12', style:'padding-top:20px' %>
            <%end%>
            <% if a.pictures[0] == nil %>
            <img src="http://www.agetruck.com/truck_img/default.gif" alt="Smiley face" class="col-xs-12">

            <%end%>
            <div class="project-description">
              <h3><%= a.title %></h3>
              <%= a.description %>
            </div>
            <% if current_user %>
              <div class="project-edit-delete">
                <%= button_to 'Delete', achievement_destroy_path(toDelete: a.id), class:"button"%>
              </div>
            <% end %>
          </div>
        <% end %>
      <% else %>
        <div class="project-container-item">
          <div class="project-description">
            <h3>There are no achievements</h3>
          </div>
        </div>

        <!-- if 4 blocks then add a new row -->
        <% if i == 4 %>
          </div>
          <div class="row">
        <% end %>
      <% end %>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-md-12">
    <%= link_to "Add new achievement", achievements_path %>
  </div>
</div>