config/routes.rb
Rails.application.routes.draw do

  get 'register' => 'users#new', as: 'users'
  post 'register' => 'users#create'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  get 'logout' => 'sessions#destroy'

  get 'project_registration' => 'projects#new', as: 'projects'
  post 'project_registration' => 'projects#create'
  post 'project_delete' => 'projects#destroy'
  get 'projects/edit' => 'projects#edit', as: 'project'
  post 'projects/update'
  get 'projects/viewproject'
  post 'projects/viewproject' => 'reviews#create'

  get 'my_project' => 'projects#show'

  get 'admin_panel' => 'sessions#admin_panel'
  post 'admin_panel' => 'sessions#password_changed'

  get 'achievement/show'
  get 'achievement/new', as:'achievements'
  post 'achievement/new' => 'achievement#create'
  post 'achievement/destroy'

  get 'users/show_achievement'

  get 'show' => 'sessions#show'

  get 'review/show'
  get 'review/new', as:'reviews'
  post 'review/new' => 'review#create'

  get 'confirm/:id' => 'sessions#confirmation'

  get 'home/index'

  root 'home#index'

end

app/models/project.rb
class Project < ActiveRecord::Base
  belongs_to :user
  has_many :reviews
  has_many :pictures
  serialize :pictures

  mount_uploaders :pictures, PictureUploader

  validates :title,
            :uniqueness => true,
            :presence => true,
            :length => {
              in: 5..150,
              message: "length should be between 5 and 150 characters"
            }

  validates :description,
            :presence => true,
            :length => {
              in: 5..5000,
              message: "length should be between 5 and 5000 characters"
            }
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def new
    @project = Project.new
  end

  def create
    @project = Project.new(project_params)
    if current_user.coins >= 100
      if @project.save
      give_achievement(current_user)
        current_user.projects << @project
        redirect_to my_project_path(@achiev)
        current_user.update_attribute :coins, current_user.coins - 100
        current_user.save
      else
        flash.now.alert = "cant save"
        render "new"
      end
    else
      flash.now.alert = "Insufficent coins"
      render "new"
    end
  end

 def give_achievement(current_user)
  achievementToShow = Achievement.new
   if current_user.projects.size < 1
     if @achievement = Achievement.where("title like ?", "%Getting started%").first
       if !current_user.achievements.include?(@achievement)
         current_user.achievements << @achievement
         current_user.update_attribute :coins , current_user.coins + 100
         achievementToShow = @achievement
       end
     end
   end

   if achievementToShow != nil
     flash[:achievementToShow] = achievementToShow.title
   end
 end
  def show
    if current_user == nil
      redirect_to root_url
    else
      @my_projects = current_user.projects
    end
  end

  def edit
    @project = Project.find(params[:toEdit])
  end

  def update

  end

  def viewproject
    @current_project = Project.find(params[:toFind])
    @review = Review.new
  end

  def destroy
    project = Project.find(params[:toDelete])
    project.destroy

    redirect_to root_url
  end

  private
  def project_params
    params.require(:project).permit(:title, :description, {pictures: []})
  end

end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/edit.html.erb
<div class="row">
  <div class="col-md-4">
    <!-- empty -->
  </div>
  <div class="form_input">
    <%= form_for @project do |f|%>
        <p><%= f.text_field :title, size:'50', class:"input_field", placeholder:'Title' %></p>
        <p><%= f.text_area :description, size:'55x10', placeholder:'Description' %></p>
        <p><%= f.submit "Update", class:'button' %></p>
    <% end %>
    <% if flash[:alert].present? %>
      <p class="alert"><%= flash[:alert] %></p>
    <% end %>
  </div>
  <div class="col-md-4">
    <!-- empty -->
  </div>
</div>

app/views/projects/new.html.erb
<div class="row">
  <div class="col-md-4">
    <!-- empty -->
  </div>
  <div class="form_input">
    <%= form_for @project do |f|%>
        <p><%= f.text_field :title, class:"input_field col-xs-12", placeholder:'Title' %></p>
        <p><%= f.text_area :description,class:"col-xs-12 input_filed2", placeholder:'Description' %></p>
        <p><%= f.file_field :pictures, multiple: true %></p>
        <p><%= f.submit "Add", class:'button' %> </p>
        <p><%= label_tag '100', nil,  style:'font-size:15px' %><%= image_tag("coin.png", size: "25x25") %></p>
    <% end %>
    <% if flash[:alert].present? %>
      <p class="alert"><%= flash[:alert] %></p>
    <% end %>
  </div>
  <div class="col-md-4">
    <!-- empty -->
  </div>
</div>

app/views/projects/show.html.erb
<script>
  $('document').ready(function() {
    setTimeout(function() {
      $('.projectAchievement').slideUp();
    }, 2000);
  });
</script>
<div class="row">
  <div class="project-container">
    <div class="row">
      <% if flash[:achievementToShow].present? %>
          <div class="col-sm-4"></div>
          <div class="projectAchievement">
            New Achievement: <br/>
            <% @achiev = Achievement.find_by_title(flash[:achievementToShow]) %>
            <br/>
            <%= image_tag @achiev.pictures[0], size:'100x100' %>
            <%= flash[:achievementToShow] %>
          </div>
          <div class="col-sm-4"></div>
      <% end %>
    </div>
  </div>
</div>
<div class="row">
  <div class="project-container">
    <div class="row">
      <div class="project-container-title">
        <h2>My Projects</h2>
      </div>
    </div>
    <% i = 0 %>
    <div class="row">
      <% if @my_projects.any? %>
        <% @my_projects.each do |mp| %>
        <% i = i + 1 %>
          <div class="project-container-item">
            <% if mp.pictures[0] != nil %>
              <%= image_tag mp.pictures[0], size:'250x250', style:'padding-top:20px' %>
            <% else %>
              <img src="http://wordpress.smartaddons.com/themes/sw_chamy/wp-content/themes/sw_chamy/assets/img/no-thumbnail.png" width="250px" height="250px" style="padding-top:20px"/>
            <% end %>
            <div class="project-description">
              <h3><%= mp.title %></h3>
              <%= mp.description %>
            </div>
            <% if current_user %>
              <div class="project-edit-delete">
                <%#= link_to 'Edit', project_path(toEdit: mp.id), class:"button", style:"float:left"%>
                <%= button_to 'Delete', project_delete_path(toDelete: mp.id), class:"button"%>
              </div>
            <% end %>
          </div>

          <!-- if 4 blocks then add a new row -->
          <% if i == 4 %>
            </div>
            <div class="row">
          <% end %>
        <% end %>
        <% else %>
        <div class="project-container-item">
          There are no projects
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/projects/viewproject.html.erb
<div class="row">
  <div class="col-md-3"></div>
  <div class="project-view-container-item">
    <div class="project-description">
      <h3><%= @current_project.title %><br></h3>
      <%= @current_project.rating %> <%= image_tag('coin.png', size:'25x25') %>
      <br>
      <%= @current_project.description %>
    </div>
    <div style="margin-bottom:5%">
      <% for i in 0..@current_project.pictures.size - 1 %>
        <% if @current_project.pictures[i] != nil %>
          <%= image_tag(@current_project.pictures[i], width:'200', style:'margin: 0 1%') %>
        <%end%>
      <%end%>
    </div>
  </div>
  <div class="col-md-3"></div>
</div>

<div class="row">
  <div class="col-md-3">
    <!-- empty -->
  </div>
  <div class="review_input">
    <% if !@current_project.reviews.any? && current_user.projects.include?(@current_project) %>
      <h3 style="text-align:center">There are no reviews</h3>
    <% end %>
    <% if @current_project.reviews.any? %>
      <h3 style="text-align:center">Reviews</h3>
      <% @current_project.reviews.each do |rev| %>
        <div class="project-review-container-item">
          <div class="project-description">
            <h5 style="text-align:left"><%= rev.user.username %></h5>
            <h3><%= rev.title %></h3>
            <%= rev.content %>
          </div>
        </div>
      <% end %>
    <% end %>

    <% if !current_user.projects.include?(@current_project) %>
      <%= form_for @review do |f|%>
          <h3 style="text-align:center">Add new Review</h3>
          <p><%= f.text_field :title, size:'50', class:"input_field", placeholder:'Title' %></p>
          <p><%= f.text_area :content, size:'55x10', placeholder:'Content' %></p>
          <p>Rating <%= select_tag 'rating', "<option>1</option><option>2</option><option>3</option><option>4</option><option>5</option>".html_safe %></p>
          <p><%= f.button :Add, name: 'toFind', value: @current_project.id , class:'button' %> </p>
      <% end %>
      <% if flash[:alert].present? %>
        <p class="alert"><%= flash[:alert] %></p>
      <% end %>
    <% end %>

  </div>
  <div class="col-md-3">
    <!-- empty -->
  </div>
</div>