config/routes.rb
Rails.application.routes.draw do

  get 'register' => 'users#new', as: 'users'
  post 'register' => 'users#create'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  get 'logout' => 'sessions#destroy'

  get 'project_registration' => 'projects#new', as: 'projects'
  post 'project_registration' => 'projects#create'
  post 'project_delete' => 'projects#destroy'
  get 'projects/edit' => 'projects#edit', as: 'project'
  post 'projects/update'
  get 'projects/viewproject'
  post 'projects/viewproject' => 'reviews#create'

  get 'my_project' => 'projects#show'

  get 'admin_panel' => 'sessions#admin_panel'
  post 'admin_panel' => 'sessions#password_changed'

  get 'achievement/show'
  get 'achievement/new', as:'achievements'
  post 'achievement/new' => 'achievement#create'
  post 'achievement/destroy'

  get 'users/show_achievement'

  get 'show' => 'sessions#show'

  get 'review/show'
  get 'review/new', as:'reviews'
  post 'review/new' => 'review#create'

  get 'confirm/:id' => 'sessions#confirmation'

  get 'home/index'

  root 'home#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>I Have An Idea</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

    <%= javascript_include_tag 'https://js.stripe.com/v2/' %>

    <%= csrf_meta_tags %>

</head>
<body>
  <div class="container-fluid">
    <div class="row">
      <div class="search-box">
        <% if current_user && !current_user.isAdmin %>
          <%= image_tag("coin.png", size: "25x25") %>
          <%= current_user.coins %>
        <% end %>
      </div>
      <div class="col-md-6">
        <!-- empty -->
      </div>
      <% if current_user == nil %>
        <%= link_to 'Login', login_path, class:'top-menu-links' %>
        <%= link_to 'Register', register_path, class:'top-menu-links' %>
        <%= link_to "", root_url, class:'top-menu-links' %>
        <%= link_to "", root_url, class:'top-menu-links' %>
      <% else %>
        <% if current_user.isAdmin == false %>
          <%= link_to 'New Project', project_registration_path, class:'top-menu-links' %>
          <%= link_to 'My Projects', my_project_path, class:'top-menu-links' %>
          <%= link_to 'Achievements', users_show_achievement_path, class:'top-menu-links' %>
          <%= link_to 'Logout', logout_path, class:'top-menu-links' %>
        <% else %>
          <%= link_to 'Achievements', achievement_show_path, class:'top-menu-links' %>
          <%= link_to 'Show Projects', show_path, class:'top-menu-links' %>
          <%= link_to 'Admin Panel', admin_panel_path, class:'top-menu-links' %>
          <%= link_to 'Logout', logout_path, class:'top-menu-links' %>
        <% end %>
      <% end %>

    </div>

    <div class="header">
      <div class="col-md-12">
        <h1><%= link_to 'I Have an Idea', root_url, style:'text-decoration:none; color:black' %></h1>
      </div>
    </div>
    <%= yield %>
  </div>
</body>
</html>